export type { ButtonProps } from "./IButtonProps";
export type { UserProps } from "./IUserProps";
export type { ProductProps } from "./IProductProps";
export type { CardProductProps } from "./ICardProductProps";
export type { CardContactProps } from "./ICardContactProps";
export type { CardNameLocationProps } from "./ICardNameLocationProps";
export type { PresentationInfoCardProps } from "./IPresentationInfoCardProps";
export type { AvaliationProps } from "./IAvaliation";
export type { TabsProps } from "./ITabs";
